component: cart
params: "REDIS_HOST:prod.elasticache.endpoint,CATALOGUE_HOST:catalogue,CATALOGUE_PORT:8080"

resources:
   limits:
     cpu: 100m
     memory: 350Mi
   requests:
     cpu: 200m
   memory: 256Mi

##we can directly connect to the other services within kub cluster

#In resources,request is requesting min resource and limit is beyong request we will get resources(limits is bonus)